#build-step
stages:
  - build
  - deploy

build-job:
  stage: build
  image: node:latest
  script:
    - npm i
    - npm run build
  artifacts:
    expire_in: 30 days
    paths:
      - dist
    

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r dist/* public
  artifacts:
    paths:
      - public